### ISSUE TITLE
 too much captcha

### ISSUE THREAD

**Issue by ulamnet** [Porco-Rosso/Butane#25]
Hello , when ı search music , get this error : Oops, something went wrong : Flood control: too much captcha requests

How to fix? thanks.

**Comment by Porco-Rosso** [comment]
Does this happen when loading a playlist or when searching for music individually?

It appears my vk Api is being used too much.

Have you filled in a captcha?

**Comment by Porco-Rosso** [comment]
You can either wait for the error to go away (should be fine tomorrow), or you can fetch your own api key and run it from your computer.

To do so, [download the repo](https://github.com/Porco-Rosso/Butane/archive/master.zip) onto your computer, open up the file app.js file in the js folder and follow these instructions:

`	/* ========================================================================
	 * To get your own token you need first create vk application at https://vk.com/editapp?act=create
	 * Then  get your APP_ID and CLIENT_SECRET at application settings
	 * Now open this url from your logged in to vk browser, this will redirect to blank.html with your token in the url bar:
	 * https://oauth.vk.com/authorize?client_id=APP_ID&client_secret=CLIENT_SECRET&scope=audio,offline&response_type=token
	 *======================================================================== */`

Right below you should see:
`var vkConfig = {
		url: "https://api.vk.com/method/audio.search",
		sort: 2,
		autoComplete: 0,
		accessToken: "ccd09c5c990069316002d28ab7f0e0ba5841fbcdc626c0524afbe4faea92451ea43a4240cab3de8eda4df",
		count: 300
	};`
Replace the access token with your own.
Open the index.html file, and it should work!

**Comment by Porco-Rosso** [comment]
I'm assuming your problem was solved. Closing this.
